# mkdocs.yml
site_name: API Docs Demo

nav:
  - Home: index.md
  - API:
      - Overview: api/readme.md
  - Dummy: 'dummy.md'  # <-- Add this line
site_url: https://sdineshkumar76.github.io/docs-practice/
